[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXTAUTH_URL = "https://nextmove-cargo.netlify.app"
  NEXTAUTH_SECRET = "nextmove-cargo-secret-key-2024-production-32chars"
